Data model day1
IsmailChangezi/blogsphere pull request #1
Opened 2023-08-15 12:03 UTC by IsmailChangezi

## Description 
- Setup and Intialise Rails
- Setup and Initialize Linters 
- Fix Linter Errors 
- Create Database 
- Create Migrations

2023-08-15 15:05 UTC, muneebulrehman requested changes
Hi @IsmailChangezi , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Great job setting up the project
- Great job running the migration files.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-15 15:05 UTC, muneebulrehman commented on db/migrate/20230815113642_create_comments.rb
> +      t.references :users, null: false, foreign_key: true
As per the ER diagram provided to you, the relation between the comments and the user is set up through the author just like for the posts. Kindly update your code just like you did for the posts.

2023-08-15 15:05 UTC, muneebulrehman commented on db/migrate/20230815113802_create_likes.rb
> +      t.references :users, null: false, foreign_key: true
As per the ER diagram provided to you, the relation between the like and the user is set up through the author just like for the posts. Kindly update your code just like you did for the posts.

2023-08-16 10:32 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @IsmailChangezi, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementingthechangesrequestedbythepreviousreviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Created migration file for `users`, `posts`, `comments` & `likes` ✔️
- Migrate all file to the schema ✔️ 
- Good use of Git flow ✔️

## Optional changes

- [ ] Please note, for future purposes kindly make your `commit` messages more descriptive and professional. here is a [link](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8) for more info

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 10:40 UTC, merged