Processing Data in Models: Day 3
IsmailChangezi/blogsphere pull request #2
Opened 2023-08-16 12:20 UTC by IsmailChangezi

## Description 
- Create Models for the tables 
- Fix Linter Errors

2023-08-16 13:09 UTC, julie-ify requested changes
## Hi @IsmailChangezi,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 13:09 UTC, julie-ify commented on app/models/user.rb
> +end
- [ ] The User model should have for returning the 3 recent posts.

  ```
  def recent_post
    posts.order('created_at Desc').limit(3)
  end
  ```

2023-08-16 13:09 UTC, julie-ify commented on app/models/post.rb
> +end
- [ ] The Post model should have a method for returning the 5 recent comments.

- [ ] It should also have a method for incrementing the posts counter of the author.

  ```
  class Post < ApplicationRecord
    belongs_to :author, class_name: 'User'
    has_many :likes
    has_many :comments, foreign_key: :posts_id
    after_save :update_posts_counter

    def recent_comments
      comments.order(created_at: :desc).limit(5)
    end

    private

    def update_posts_counter
      author.increment!(:posts_counter)
    end
  end
  ```

2023-08-16 13:09 UTC, julie-ify commented on app/models/comment.rb
> +end
- [ ] The Comment model should have a method for updating the comments count of a post.

- [ ] **[OPTIONAL]** Optionally, it would be nice to attach a callback for it.

  ```
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
  ```

2023-08-16 13:09 UTC, julie-ify commented on app/models/like.rb
> +  end
- [ ] The Like model should have a method for updating the comments count of a post.

- [ ] **[OPTIONAL]** Optionally, it would be nice to attach a callback for it.

  ```
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
  ```

2023-08-17 07:43 UTC, VICTOR-CHUKWU requested changes
Hi @IsmailChangezi , 
## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-08-17 07:43 UTC, VICTOR-CHUKWU commented on app/models/post.rb
> +    end
- [ ] you are still missing one method which is
```
 def update_post_counter
    author.increment!(:posts_counter)
  end
```
kindly fix this

2023-08-17 08:03 UTC, danmainah approved these changes
Hi @IsmailChangezi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented the change requested to ensure all custom methods are added.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 08:03 UTC, danmainah commented on app/models/post.rb
> +
- [ ] [optional] @IsmailChangezi Great work implementing the change requested, however, I would encourage the use of a private method in a case like this where the `post_counter_update` is a private method called by [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - after_save whenever a user adds a new post.

2023-08-18 07:09 UTC, merged